# Generated by Django 5.2.3 on 2025-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Location', models.CharField()),
                ('description', models.CharField()),
                ('Cost', models.IntegerField()),
                ('free_or_nor', models.BooleanField(default=False)),
                ('image', models.CharField()),
            ],
            options={
                'db_table': 'solutions',
            },
        ),
    ]
