# Generated by Django 5.2.3 on 2025-08-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('phone', models.CharField()),
                ('adress', models.CharField()),
                ('gender', models.CharField()),
                ('age', models.CharField()),
                ('is_admin', models.BooleanField()),
                ('last_name', models.CharField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RenameField(
            model_name='solutions',
            old_name='free_or_nor',
            new_name='free_or_not',
        ),
    ]
